import type { GameState } from "@/lib/gameState";

export type RecommendationDifficulty = "LOW" | "MODERATE" | "HIGH";
export interface PolicyRecommendation { id: string; advisorRole: "economic" | "security" | "foreign" | "social" | "chief_of_staff"; title: string; rationale: string; action: string; institution: string; difficulty: RecommendationDifficulty; score: number; relatedEntityIds: string[]; generatedTurn: number; }

export function generatePolicyRecommendations(state: GameState): PolicyRecommendation[] {
  const list: PolicyRecommendation[] = [];
  const add = (item: Omit<PolicyRecommendation, "generatedTurn">) => list.push({ ...item, generatedTurn: state.turn });
  if (state.inflation > 5) add({ id: "inflation-control", advisorRole: "economic", title: "Restore price stability", rationale: `Inflation is ${state.inflation.toFixed(1)}%, above the 3% target and weakening household purchasing power.`, action: "Coordinate a credible anti-inflation package with the independent Central Bank and contain unfunded spending.", institution: "Central Bank / Ministry of Finance", difficulty: "HIGH", score: 70 + state.inflation, relatedEntityIds: [] });
  if (state.fiscal.debtToGDP > 90 || state.fiscal.nominalBalance < -900) add({ id: "fiscal-consolidation", advisorRole: "economic", title: "Stabilise the debt trajectory", rationale: `Debt is ${state.fiscal.debtToGDP.toFixed(1)}% of GDP and the annual nominal balance is R$${state.fiscal.nominalBalance.toFixed(0)}bn.`, action: "Prepare a funded consolidation package and review low-priority recurring commitments.", institution: "National Congress", difficulty: state.congressionalSupport >= 55 ? "MODERATE" : "HIGH", score: 82, relatedEntityIds: state.fiscal.ledger.slice(-3).map((e) => e.actionId) });
  const threat = [...state.criminalOrganisations].sort((a, b) => b.capacity - a.capacity)[0];
  if (threat && threat.capacity >= 60) add({ id: `security-${threat.id}`, advisorRole: "security", title: `Pressure ${threat.shortName} networks`, rationale: `${threat.name} retains ${Math.round(threat.capacity)}% operational capacity and is ${threat.trend}.`, action: "Increase intelligence preparation and target financial and command infrastructure before wider deployment.", institution: "Federal Police / Ministry of Justice", difficulty: "HIGH", score: threat.capacity, relatedEntityIds: [threat.id] });
  if (state.congressionalSupport >= 60) add({ id: "coalition-opportunity", advisorRole: "chief_of_staff", title: "Use the legislative window", rationale: `Coalition strength is ${Math.round(state.congressionalSupport)}%, creating favourable conditions for a disciplined reform package.`, action: "Advance one priority bill before coalition demands fragment the available majority.", institution: "National Congress", difficulty: "MODERATE", score: state.congressionalSupport, relatedEntityIds: [] });
  if (state.congressionalSupport < 40) add({ id: "coalition-repair", advisorRole: "chief_of_staff", title: "Repair the governing coalition", rationale: `Congressional support has fallen to ${Math.round(state.congressionalSupport)}%, leaving major legislation exposed.`, action: "Open targeted negotiations with swing parties before introducing another structural bill.", institution: "Presidency / National Congress", difficulty: "HIGH", score: 100 - state.congressionalSupport, relatedEntityIds: state.legislativeProceedings.filter((p) => !["PASSED", "FAILED", "WITHDRAWN"].includes(p.status)).map((p) => p.id) });
  const failedBill = [...state.legislativeProceedings].reverse().find((item) => item.status === "FAILED" && (item.voteResult?.turn ?? -1) >= state.turn - 2);
  if (failedBill) add({ id: `failed-bill-${failedBill.id}`, advisorRole: "chief_of_staff", title: `Reassess ${failedBill.title}`, rationale: `The measure failed bicameral passage in Turn ${failedBill.voteResult?.turn}; its policy effects were not implemented.`, action: "Review the vote, narrow the proposal or rebuild support before deciding whether to reintroduce it.", institution: "Presidency / National Congress", difficulty: "HIGH", score: 78, relatedEntityIds: [failedBill.id] });
  if (state.unemployment > 11 || state.approval < 40) add({ id: "household-pressure", advisorRole: "social", title: "Address household insecurity", rationale: `Unemployment is ${state.unemployment.toFixed(1)}% and presidential approval is ${Math.round(state.approval)}%.`, action: "Prioritise targeted employment and service-delivery measures with identified funding.", institution: "Presidency / National Congress", difficulty: "MODERATE", score: 65 + Math.max(0, 40 - state.approval), relatedEntityIds: [] });
  if (state.internationalPressure > 35) add({ id: "international-pressure", advisorRole: "foreign", title: "Reduce external exposure", rationale: `International pressure has reached ${Math.round(state.internationalPressure)} out of 100.`, action: "Brief major partners and present verifiable safeguards around the policy drawing scrutiny.", institution: "Itamaraty", difficulty: "MODERATE", score: state.internationalPressure, relatedEntityIds: [] });
  for (const project of state.projects.filter((p) => p.lifecycle.status === "STALLED" || p.lifecycle.status === "FAILED")) add({ id: `delivery-${project.id}`, advisorRole: "chief_of_staff", title: `${project.lifecycle.status === "FAILED" ? "Account for" : "Unblock"} ${project.name}`, rationale: `${project.name} is ${project.lifecycle.status.toLowerCase()} at ${Math.round(project.lifecycle.progress)}% completion.`, action: project.lifecycle.status === "STALLED" ? "Review its financing and delivery constraint before the next turn." : "Publish an implementation review and decide whether the objective needs a replacement programme.", institution: "Responsible ministry / Presidency", difficulty: "HIGH", score: project.lifecycle.status === "FAILED" ? 90 : 75, relatedEntityIds: [project.id] });
  return list.sort((a, b) => b.score - a.score).slice(0, 8);
}
