"use client";
import { Check, X } from "lucide-react";
import type { InteractiveEncounter } from "@/lib/encounters";

const ROLE_LABELS = { economic: "Economic adviser", security: "Security adviser", social: "Social adviser", foreign: "Foreign minister", chief_of_staff: "Political adviser" } as const;
interface Props { encounter: InteractiveEncounter; onStart: () => void; onAnswer: (questionId: string, responseId: string) => void; onClose: () => void; }

export function InterviewEncounter({ encounter, onStart, onAnswer, onClose }: Props) {
  const question = encounter.decisionNodes[encounter.currentNode];
  const journalist = encounter.participants.find((p) => p.type === "JOURNALIST");
  return <div className="fixed inset-0 z-[90] overflow-y-auto bg-[#080c14]/95 px-4 py-8" role="dialog" aria-modal="true" aria-label={encounter.title}>
    <main className="mx-auto max-w-4xl border border-border bg-background shadow-2xl">
      <header className="flex items-start justify-between border-b border-border px-6 py-5"><div><p className="sovereign-kicker">{journalist?.role ?? "National media"}</p><h2 className="sovereign-title mt-1 text-2xl">Presidential Interview</h2><p className="mt-2 text-xs text-text-muted">{encounter.location} · {encounter.date}</p></div><button type="button" onClick={onClose} className="p-2 text-text-muted hover:text-text" aria-label="Close interview"><X size={18}/></button></header>
      {encounter.status === "ACCEPTED" && <section className="px-6 py-12 text-center"><p className="mx-auto max-w-2xl font-serif text-xl leading-8 text-text">The interview will cover {encounter.topics.slice(0, 3).join(", ")}.</p><p className="mx-auto mt-3 max-w-xl text-sm leading-6 text-text-muted">Your answers will be judged against the current national situation. Adviser guidance is an assessment, not a guarantee.</p><button type="button" onClick={onStart} className="mt-7 bg-accent px-7 py-3 text-sm font-semibold text-white hover:bg-accent/90">Begin interview</button></section>}
      {encounter.status === "COMPLETED" && <section className="px-6 py-10"><div className="mx-auto max-w-2xl"><Check className="text-positive" size={26}/><p className="sovereign-kicker mt-4">Interview complete</p><h3 className="mt-2 font-serif text-2xl text-text">The interview concluded after {encounter.responses.length} questions.</h3><p className="mt-5 text-sm text-text-muted">Initial assessment</p><ul className="mt-3 space-y-2 border-l-2 border-brass pl-4 text-sm text-text">{encounter.outcome?.themes.map((theme) => <li key={theme}>{theme} dominated part of the discussion.</li>)}<li>Media coverage will follow from the recorded exchange.</li></ul><button type="button" onClick={onClose} className="mt-7 border border-border px-6 py-2.5 text-sm font-semibold text-text hover:bg-panel">Return to the front page</button></div></section>}
      {encounter.status === "IN_PROGRESS" && question && <section className="px-6 py-6"><div className="flex justify-between border-b border-border pb-4 text-[10px] uppercase tracking-[0.18em] text-text-muted"><span>{question.topic}</span><span>Question {encounter.currentNode + 1} of {encounter.decisionNodes.length}</span></div><div className="py-7"><p className="text-xs font-semibold uppercase tracking-wider text-accent">{journalist?.displayName}</p><blockquote className="mt-3 max-w-3xl font-serif text-xl leading-8 text-text">“{question.displayQuestion}”</blockquote></div><div className="space-y-3">{question.responseOptions.map((option, index) => <button key={option.id} type="button" onClick={() => onAnswer(question.id, option.id)} className="grid w-full grid-cols-[2rem_1fr] gap-3 border border-border bg-panel/35 p-4 text-left hover:border-accent/60 hover:bg-panel/65"><span className="font-serif text-lg text-brass">{String.fromCharCode(65 + index)}</span><span><span className="block text-xs font-semibold uppercase tracking-wider text-text">{option.label}</span><span className="mt-2 block text-sm leading-6 text-text-muted">“{option.displayText}”</span><span className="mt-3 block border-l border-border pl-3 text-xs leading-5 text-text-muted"><b className="text-text">{ROLE_LABELS[option.assessment.advisorRole]}:</b> {option.assessment.text}<br/><span className="uppercase tracking-wider">Confidence: {option.assessment.confidence}</span></span></span></button>)}</div></section>}
    </main>
  </div>;
}
